{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Összesítő statisztikák", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Összesített késés",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "query": "from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\")\r\n  |> window(every: 1d)\r\n  |> last()\r\n  |> group()\r\n  |> sum()",
     "rawSql": "SELECT SUM(\"Delay\") AS \"TotalDelay\" FROM \"trains\" WHERE \"time\" >= $__timeFrom AND \"time\" <= $__timeTo AND \"Menetvonal\" = 'MAV' GROUP BY \"TrainNumber\" LIMIT 1"
    }
   ]
  },
  {
   "title": "Egy vonatra eső átlagos késés",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\")\r\n  |> window(every: 1d)\r\n  |> last()\r\n  |> group()\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Késés toplista",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\")\r\n  |> window(every: 1d)\r\n  |> last()\r\n  |> group()\r\n  |> sort(columns: [\"_value\"], desc: true) \r\n  |> limit(n: 10)\r\n  |> map(fn: (r) => ({r with Rank: 1}))\r\n  |> cumulativeSum(columns: [\"Rank\"]) \r\n  |> rename(columns: {_value: \"Delay\"})\r\n  |> rename(columns: {Relation: \"Route\"})\r\n   |> keep(columns: [\"Rank\",\"_time\", \"Delay\", \"Route\"])"
    }
   ]
  },
  {
   "title": "Legnagyobb késés",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\")\r\n  |> window(every: 1d)\r\n  |> last()\r\n  |> group()\r\n  |> max()"
    }
   ]
  },
  {
   "title": "Öt percnél többet késő vonatok aránya",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "trains = from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\")\r\n  |> window(every: 1d)\r\n  |> last()\r\n  |> group() \r\n\r\ntotalCount = trains\r\n  |> count()\r\n  |> set(key: \"joinKey\", value: \"1\")\r\n\r\ndelayedCount = trains\r\n  |> filter(fn: (r) => r._value >= 5) \r\n  |> count()\r\n  |> set(key: \"joinKey\", value: \"1\") \r\n\r\nresult = join(tables: {totalCount: totalCount, delayedCount: delayedCount}, on: [\"joinKey\"])\r\n  |> map(fn: (r) => ({\r\n      _value: float(v: r._value_delayedCount) / float(v: r._value_totalCount)\r\n  }))\r\n\r\nresult\r\n"
    }
   ]
  },
  {
   "title": "Élő vasútközlekedés",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "trains = from(bucket: \"mav\")\r\n  |> range(start: -1m, stop: now())\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")  // Pivot Lat, Lng, and Delay into columns\r\n      |> rename(columns: {Lat: \"latitude\",Lon:\"longitude\"})\r\n  |> group()\r\n\r\ntrains\r\n"
    }
   ]
  },
  { "title": "Grafikonok", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Közlekedő vonatok összesített késése",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "trains = from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\") \r\n  |> window(every: v.windowPeriod, createEmpty: false)\r\n  |> last()\r\n  |> group()\r\n\r\n\r\ntrains \r\n  |> window(every: v.windowPeriod, createEmpty: false)\r\n  |> sum()\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Öt percet meghaladó késés aránya",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "trains = from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\")  // Access the Delay field\r\n  |> window(every: v.windowPeriod, createEmpty: false)\r\n  |> last()\r\n  |> group()\r\n\r\ndelayedCount = trains\r\n  |> filter(fn: (r) => r._value >= 5)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count , createEmpty: false) \r\n  |> rename(columns: {_value: \"DelayedCount\"})\r\n\r\ntotalCount = trains\r\n  |> aggregateWindow(every: v.windowPeriod, fn: count , createEmpty: false) \r\n  |> rename(columns: {_value: \"TotalCount\"})\r\n\r\njoin(tables: {delayedCount: delayedCount, totalCount: totalCount}, on: [\"_time\"])\r\n  |> map(fn: (r) => ({_time: r._time, Ratio: float(v: r.DelayedCount) / float(v: r.TotalCount)}))\r\n"
    }
   ]
  },
  {
   "title": "Közlekedő vonatok száma",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "trains = from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\")  // Access the Delay field\r\n    |> window(every: v.windowPeriod, createEmpty: false)\r\n  |> last()\r\n  |> group()\r\n\r\ntrains |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false) "
    }
   ]
  },
  {
   "title": "Egy vonatra eső átlagos késés",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "trains = from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\") \r\n    |> window(every: v.windowPeriod, createEmpty: false)\r\n  |> last()\r\n  |> group()\r\n\r\n\r\ntrains  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Legnagyobb késés",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "trains = from(bucket: \"mav\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"trains\")\r\n  |> filter(fn: (r) => r[\"Menetvonal\"] == \"MAV\")\r\n  |> filter(fn: (r) => r._field == \"Delay\") \r\n  |> group()\r\n\r\ntrains |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)"
    }
   ]
  }
 ]
}